papp_flask/__init__.py
# Import the Flask basics
from flask import Flask, flash, redirect, url_for
from flask_bootstrap import Bootstrap
import logging


# Define the App
app = Flask(__name__)
app.config.from_pyfile('../config.py')

Bootstrap(app)

#
# Module Imports
#

# Import the module / component using their blueprints
from papp_flask.home.views import home

# Register Blueprints
app.register_blueprint(home)

papp_flask/home/views.py
from flask import Blueprint, render_template, request, flash
import requests
import base64
import io
import os
import cairosvg
from PIL import Image

# Replace with your Alchemy API key
ALCHEMY_API_KEY = os.getenv('ALCHEMY_API_KEY')

# Define the PAPP contract address
CONTRACT_ADDRESS = "0xF39bE779905D16fE23B2cC1297Dc3e759D2dAA11"

home = Blueprint('home', __name__)


def upscale_svg(svg_data, new_width, new_height):
    # Render the SVG to a PNG surface with the desired dimensions
    png_bytes = cairosvg.svg2png(bytestring=svg_data, parent_width=new_width, parent_height=new_height)
    # Convert the PNG bytes to a PIL image
    pil_image = Image.open(io.BytesIO(png_bytes))
    return pil_image


@home.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        ethereum_address = request.form.get('ethereum_address', None)
        tokenid = request.form.get('tokenid', None)
        if ethereum_address:
            # print(ethereum_address)
            url = f"https://base-mainnet.g.alchemy.com/nft/v3/{ALCHEMY_API_KEY}/getNFTsForOwner?owner={ethereum_address}&contractAddresses[]={CONTRACT_ADDRESS}&withMetadata=true&orderBy=transferTime&pageSize=100"
            headers = {"accept": "application/json"}
            response = requests.get(url, headers=headers)
            data = response.json()

            nfts = []
            if 'ownedNfts' in data:
                for nft in data['ownedNfts']:
                    if 'name' in nft and 'tokenId' in nft and 'image' in nft and 'originalUrl' in nft['image']:
                        name = nft['name']
                        token_id = nft['tokenId']
                        description = nft['description']
                        svg_base64 = nft['image']['originalUrl'].split(',')[1]
                        svg_data = base64.b64decode(svg_base64)
                        upscaled_image = upscale_svg(svg_data, 1024, 1024)
                        # Convert PIL image to bytes
                        png_bytes = io.BytesIO()
                        upscaled_image.save(png_bytes, format='PNG')
                        png_bytes = png_bytes.getvalue()
                        # Encode PNG image as base64
                        base64_png = base64.b64encode(png_bytes).decode()
                        nfts.append({
                            'name': name,
                            'tokenId': token_id,
                            'description': description,
                            'image': base64_png
                        })
                return render_template('index.html', nfts=nfts)
            flash("No image found for the provided Ethereum address")
            return render_template('index.html')
        # User provided a tokenId
        if tokenid:
            # print(tokenid)
            url = f"https://base-mainnet.g.alchemy.com/nft/v3/{ALCHEMY_API_KEY}/getNFTMetadata?contractAddress={CONTRACT_ADDRESS}&tokenId={tokenid}&refreshCache=false"
            headers = {"accept": "application/json"}
            response = requests.get(url, headers=headers)
            data = response.json()
            nfts = []
            if data['name'] is None:
                # TokenID not found AKA 100001+
                flash("No tokenID found")
                return render_template('index.html')

            if 'name' in data and 'tokenId' in data and 'image' in data and 'originalUrl' in data['image']:
                name = data['name']
                token_id = data['tokenId']
                description = data['description']
                svg_base64 = data['image']['originalUrl'].split(',')[1]
                svg_data = base64.b64decode(svg_base64)
                upscaled_image = upscale_svg(svg_data, 1024, 1024)
                # Convert PIL image to bytes
                png_bytes = io.BytesIO()
                upscaled_image.save(png_bytes, format='PNG')
                png_bytes = png_bytes.getvalue()
                # Encode PNG image as base64
                base64_png = base64.b64encode(png_bytes).decode()
                nfts.append({
                    'name': name,
                    'tokenId': token_id,
                    'description': description,
                    'image': base64_png
                })
            return render_template('index.html', nfts=nfts)
        else:
            flash("No tokenID found")
            return render_template('index.html')
    # We are here on a GET request
    else:
        return render_template('index.html')

papp_flask/templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">

    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>PAPP as PNG</title>

    <!-- Bulma Import -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">

    <!-- Bulma Social Sharing Import -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-social@2/css/all.min.css" />

    <!--Font Awesome-->
    <link
            rel="stylesheet"
            href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
            integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
            crossorigin="anonymous"
    >

</head>

<body>

<!-- Navbar -->
<nav class="navbar is-black" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
  <img src="{{ url_for('static', filename='6696_128x128.gif') }}" alt="6696 128x128 GIF" width="32" height="32" class="mr-2">
  <strong>PAPP as PNG</strong>
</a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <!-- Add other navbar items here -->
    </div>

    <div class="navbar-end">
    <!-- search by tokenId -->
      <div class="navbar-item">
        <form action="{{ url_for('home.index') }}" method="post">
          <div class="field has-addons">
            <div class="control">
              <input class="input" type="text" name="tokenid" placeholder="Enter Token Number">
            </div>
            <div class="control">
              <button class="button is-link" type="submit">Get One PAPP!</button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <!-- search by Ethereum Address -->
      <div class="navbar-item">
        <form action="{{ url_for('home.index') }}" method="post">
          <div class="field has-addons">
            <div class="control">
              <input class="input" type="text" name="ethereum_address" placeholder="Enter Ethereum Address">
            </div>
            <div class="control">
              <button class="button is-success" type="submit">Get PAPPs!</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</nav>

<!-- Content -->
<section class="section">
 <!-- messages from FLask -->
  {% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="notification is-link is-light">
      <button class="delete"></button>
        {{ messages[0] }}
      </div>
      {% endif %}
  {% endwith %}

  <div class="container">
    <!-- content block -->
    {% block content %}{% endblock %}
  </div>
</section>

<!-- Footer -->
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>PAPP as PNG </strong>made by <a href="https://twitter.com/BitsofJeremy">BitsofJeremy</a>
    </p>
    <img src="{{ url_for('static', filename='6696_128x128.gif') }}" alt="6696 128x128 GIF" width="32" height="32">
  </div>
</footer>

<!-- JavaScript to make burger menu work -->
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const $nbBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
        if ($nbBurgers.length < 1) {
            return;
        }
        $nbBurgers.forEach( el => {
            el.addEventListener('click', () => {
                const target = el.dataset.target;
                const $target = document.getElementById(target);
                el.classList.toggle('is-active');
                $target.classList.toggle('is-active');
            });
        });
    });
</script>

<!--    JavaScript to delete notifications. -->
<script>
    document.addEventListener('DOMContentLoaded', () => {
  (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
    const $notification = $delete.parentNode;

    $delete.addEventListener('click', () => {
      $notification.parentNode.removeChild($notification);
    });
  });
});
</script>

</body>

</html>

papp_flask/templates/index.html
<!-- templates/index.html -->

{% extends 'base.html' %}
{% block content %}

<section class="section">
    <div class="container">
        <h1 class="title">Welcome to PAPP as PNG: The PunkApepen to PNG Maker</h1>
<div class="content">
    <p><strong>Instructions:</strong></p>
    <ol>
        <li><strong>Enter your Ethereum wallet address or NFT token ID in the form above.</strong><br>
            <em>Provide either your Ethereum wallet address or the token ID of your NFT. You cannot enter both at the same time.</em></li>
        <li><strong>Click the "GO!" button to retrieve your PunkApepen.</strong><br>
            <em>Our system will fetch all the PunkApepens associated with your Ethereum wallet address or NFT token ID and display them below.</em></li>
        <li><strong>Once your PunkApepens show up, click on each one to view and download a beautiful 1024x1024 PNG file.</strong><br>
            <em>Explore the intricate details of each of your PunkApepen NFTs and choose your favorites to download.</em></li>
        <li><strong>Make it PAPP!</strong><br>
            <em>Enjoy your collection of high-resolution PunkApepen NFTs and unleash your creativity! Share them with friends, use them as avatars, or even print them as artwork.</em></li>
    </ol>
    <p><strong>Looking for more PAPPs?</strong></p>
    <ul>
        <li><a href="https://opensea.io/collection/punkapepen-orig" target="_blank" rel="noopener noreferrer">Buy more PAPPs on OpenSea</a></li>
        <li><a href="https://magiceden.io/collections/base/0xf39be779905d16fe23b2cc1297dc3e759d2daa11" target="_blank" rel="noopener noreferrer">Buy more PAPPs on MagicEden</a></li>
        <li><a href="https://twitter.com/PunkApepen" target="_blank" rel="noopener noreferrer">Follow PunkApepen on X</a></li>
        <li><a href="https://www.punkapepen.com/" target="_blank" rel="noopener noreferrer">Visit the PunkApepen website</a></li>
    </ul>
</div>


        {% if nfts %}
        <div class="columns is-multiline">
            {% for nft in nfts %}
                <div class="column is-one-third">
                    <div class="card">
                        <div class="card-image">
                            <figure class="image is-4by3" style="height: 200px; overflow: hidden;">
                                <a href="data:image/png;base64,{{ nft.image }}" download="{{ nft.tokenId }}_PunkApepen-1024x1024.png">
                                    <img src="data:image/png;base64,{{ nft.image }}" alt="Upscaled PunkApepen Image" style="object-fit: cover; width: 100%;">
                                </a>
                            </figure>
                        </div>
                        <div class="card-content">
                            <div class="content">
                                <p>Name: {{ nft.name }}</p>
                                <p>Token ID: {{ nft.tokenId }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
        {% endif %}
    </div>
</section>

{% endblock %}